# Generated by Django 3.1.7 on 2023-06-03 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Modelos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fechaRegistro', models.DateField(blank=True, null=True)),
                ('fechaEntrega', models.DateField(blank=True, null=True)),
                ('rutaProduccion', models.JSONField(blank=True, null=True)),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Modelos.modelo')),
            ],
        ),
    ]
