# Generated by Django 3.1.7 on 2023-06-03 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='rutaProduccion',
        ),
    ]
