# Generated by Django 3.1.7 on 2023-06-07 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0003_auto_20230520_0736'),
        ('Pedidos', '0002_remove_pedido_rutaproduccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Modelos.modelo'),
            preserve_default=False,
        ),
    ]
