# Generated by Django 3.1.7 on 2023-06-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0004_auto_20230616_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fechaRegistro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
