# Generated by Django 3.1.7 on 2023-08-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0005_auto_20230617_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ordenCompra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
