# Generated by Django 3.1.7 on 2024-03-01 16:11

import apps.Pedidos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0006_pedido_ordencompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='progreso',
            field=models.JSONField(default=apps.Pedidos.models.valor_por_defecto),
        ),
    ]
