# Generated by Django 3.1.7 on 2024-03-01 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0007_pedido_progreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='progreso',
        ),
    ]
