# Generated by Django 3.1.7 on 2024-03-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0009_pedido_progreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='progreso',
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Progreso', 'Progreso'), ('Terminado', 'Terminado'), ('Stock', 'Stock'), ('No relevante', 'No relevante')], default='Progreso', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='paresProgreso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='paresTotales',
            field=models.IntegerField(default=0),
        ),
    ]
