# Generated by Django 3.1.7 on 2024-03-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0010_auto_20240312_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Terminado', 'Terminado'), ('Stock', 'Stock')], default='Pendiente', max_length=20),
        ),
    ]
