# Generated by Django 3.1.7 on 2024-03-14 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0011_auto_20240313_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
    ]
