# Generated by Django 3.1.7 on 2024-03-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0013_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('Produccion', 'Produccion'), ('Almacen', 'Almacen'), ('Muestra', 'Muestra'), (' Reposicion', 'Reposicion')], default='Produccion', max_length=20),
        ),
    ]
