# Generated by Django 3.1.7 on 2024-03-14 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0014_renombrar_campo_titulo_a_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='ordenCompra',
            new_name='ordenProduccion',
        ),
    ]
