# Generated by Django 3.1.7 on 2024-03-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0017_auto_20240314_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('Produccion', 'Produccion'), ('Almacen', 'Almacen'), ('Muestra', 'Muestra'), ('Faltante', 'Faltante'), ('Reposicion', 'Reposicion'), ('Otro', 'Otro')], default='Produccion', max_length=20),
        ),
    ]
