# Generated by Django 3.1.7 on 2023-02-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0002_remove_empleado_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='is_active',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20),
        ),
    ]
