# Generated by Django 3.1.7 on 2023-02-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0002_remove_empleado_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fechaAltaSeguro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fechaEntrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
