# Generated by Django 3.1.7 on 2023-02-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0003_empleado_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
