# Generated by Django 3.1.7 on 2023-06-16 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Maquinas', '0003_auto_20230215_2246'),
        ('Empleados', '0001_initial'),
        ('Produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('idRegistro', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('turno', models.CharField(blank=True, max_length=200, null=True)),
                ('fechaCaptura', models.DateTimeField(blank=True, null=True)),
                ('departamento', models.CharField(choices=[('Tejido', 'Tejido'), ('Corte', 'Corte'), ('Plancha', 'Plancha'), ('Empaque', 'Empaque'), ('Transporte', 'Transporte'), ('Diseno', 'Diseño'), ('Gerencia', 'Gerencia')], default='Tejido', max_length=20)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleado')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maquinas.maquina')),
                ('produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Produccion.produccion')),
            ],
        ),
    ]
