# Generated by Django 3.1.7 on 2023-12-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0003_auto_20230729_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='tipo',
            field=models.CharField(choices=[('Ordinario', 'Ordinario'), ('Reposicion', 'Reposicion'), ('Extra', 'Extra'), ('Falla', 'Falla')], default='Ordinario', max_length=20),
        ),
    ]
