# Generated by Django 3.1.7 on 2023-03-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contactos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
