# Generated by Django 3.1.7 on 2023-04-13 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0003_cliente_rfc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('idModelo', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
            ],
        ),
    ]
