# Generated by Django 3.1.7 on 2023-03-01 16:46

import apps.Modelos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
        ('Maquinas', '0003_auto_20230215_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('idModelo', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('nombrePrograma', models.CharField(max_length=200)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to=apps.Modelos.models.upload_to)),
                ('talla', models.CharField(max_length=25)),
                ('tipoMaquinaTejido', models.CharField(blank=True, max_length=100, null=True)),
                ('galga', models.CharField(blank=True, max_length=100, null=True)),
                ('velocidadTejido', models.CharField(max_length=25)),
                ('tiempoBajada', models.CharField(max_length=25)),
                ('velocidadPlancha', models.CharField(max_length=25)),
                ('temperaturaPlancha', models.CharField(max_length=25)),
                ('numeroPuntos', models.CharField(max_length=1000)),
                ('jalones', models.CharField(max_length=1000)),
                ('economisadores', models.CharField(max_length=1000)),
                ('otros', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Clientes.cliente')),
                ('maquinaPlancha', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='maquinaPlancha', to='Maquinas.maquina')),
                ('maquinaTejido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='maquinaTejido', to='Maquinas.maquina')),
            ],
        ),
    ]
