# Generated by Django 3.1.7 on 2023-05-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
