# Generated by Django 3.1.7 on 2023-03-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0002_auto_20230301_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='economisadores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='jalones',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='numeroPuntos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
