# Generated by Django 3.1.7 on 2023-04-03 22:30

import apps.Modelos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0006_auto_20230321_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='archivoFichaTecnica',
            field=models.FileField(blank=True, null=True, upload_to=apps.Modelos.models.upload_to),
        ),
    ]
