# Generated by Django 3.1.7 on 2023-04-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0006_auto_20230321_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='materiales',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='temperaturaPlancha',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='tiempoBajada',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='velocidadTejido',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
