# Generated by Django 3.1.7 on 2023-04-04 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0007_modelo_archivofichatecnica'),
        ('Modelos', '0007_auto_20230404_1146'),
    ]

    operations = [
    ]
