# Generated by Django 3.1.7 on 2023-04-04 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_auto_20230301_1539'),
        ('Modelos', '0008_merge_20230404_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='nombrePrograma',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='talla',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='velocidadPlancha',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
