# Generated by Django 3.1.7 on 2023-04-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0009_auto_20230404_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='pesoLurex',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='pesoMelt',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='pesoPoliester',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
