# Generated by Django 3.1.7 on 2023-06-04 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DetallePedido', '0002_auto_20230603_1726'),
        ('Empleados', '0001_initial'),
        ('Maquinas', '0003_auto_20230215_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('idProduccion', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('numEtiqueta', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('estacionActual', models.JSONField()),
                ('tejido', models.CharField(choices=[('-1', '-1'), ('0', '0'), ('1', '1')], default='-1', max_length=5)),
                ('capturaTejido', models.DateField(blank=True, null=True)),
                ('turnoTejido', models.CharField(blank=True, max_length=50, null=True)),
                ('plancha', models.CharField(choices=[('-1', '-1'), ('0', '0'), ('1', '1')], default='-1', max_length=5)),
                ('capturaPlancha', models.DateField(blank=True, null=True)),
                ('turnoPlancha', models.CharField(blank=True, max_length=50, null=True)),
                ('corte', models.CharField(choices=[('-1', '-1'), ('0', '0'), ('1', '1')], default='-1', max_length=5)),
                ('capturaCorte', models.DateField(blank=True, null=True)),
                ('turnoCorte', models.CharField(blank=True, max_length=50, null=True)),
                ('calidad', models.CharField(choices=[('-1', '-1'), ('0', '0'), ('1', '1')], default='-1', max_length=5)),
                ('capturaCalidad', models.DateField(blank=True, null=True)),
                ('turnoCalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('empaque', models.CharField(choices=[('-1', '-1'), ('0', '0'), ('1', '1')], default='-1', max_length=5)),
                ('capturaEmpaque', models.DateField(blank=True, null=True)),
                ('turnoEmpaque', models.CharField(blank=True, max_length=50, null=True)),
                ('stante', models.CharField(blank=True, max_length=50, null=True)),
                ('entrega', models.CharField(choices=[('-1', '-1'), ('0', '0'), ('1', '1')], default='-1', max_length=5)),
                ('capturaEntrega', models.DateField(blank=True, null=True)),
                ('cortador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cortador', to='Empleados.empleado')),
                ('detallePedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DetallePedido.detallepedido')),
                ('empacador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='empacador', to='Empleados.empleado')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inspector', to='Empleados.empleado')),
                ('maquinaCorteProduccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='maquinaCorteProduccion', to='Maquinas.maquina')),
                ('maquinaPlanchaProduccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='maquinaPlanchaProduccion', to='Maquinas.maquina')),
                ('maquinaTejidoProduccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='maquinaTejidoProduccion', to='Maquinas.maquina')),
                ('planchador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='planchador', to='Empleados.empleado')),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='repartidor', to='Empleados.empleado')),
                ('tejedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tejedor', to='Empleados.empleado')),
            ],
        ),
    ]
