# Generated by Django 3.1.7 on 2023-07-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='numEtiqueta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
