# Generated by Django 3.1.7 on 2023-06-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produccion', '0002_auto_20230604_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='estacionActual',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
