# Generated by Django 3.1.7 on 2023-06-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produccion', '0004_produccion_tallareal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='tallaReal',
            field=models.CharField(max_length=50),
        ),
    ]
