# Generated by Django 3.1.7 on 2024-01-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produccion', '0005_auto_20240130_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='tipo',
            field=models.CharField(choices=[('Ordinario', 'Ordinario'), ('Reposicion', 'Reposicion'), ('Extra', 'Extra'), ('Falla', 'Falla')], default='Ordinario', max_length=20),
        ),
    ]
