# Generated by Django 3.1.7 on 2023-05-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20230128_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='rol',
            field=models.CharField(choices=[('E', 'Encargado'), ('D', 'Desarrollador'), ('A', 'Administrador')], default='E', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('E', 'Encargado'), ('D', 'Desarrollador'), ('A', 'Administrador')], default='E', max_length=20),
        ),
    ]
