# Generated by Django 3.1.7 on 2023-02-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0002_auto_20230227_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='otro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
