# Generated by Django 3.1.7 on 2023-03-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0004_auto_20230227_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='departamento',
            field=models.CharField(choices=[('Tejido', 'Tejido'), ('Corte', 'Corte'), ('Plancha', 'Plancha'), ('Empaque', 'Empaque'), ('Transporte', 'Transporte'), ('Diseno', 'Diseño'), ('Gerencia', 'Gerencia')], default='Tejido', max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contactos',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
