# Generated by Django 3.1.7 on 2023-03-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0005_auto_20230301_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='contactos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
