# Generated by Django 3.1.7 on 2023-02-16 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maquinas', '0002_maquina_detallesadquisicion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquina',
            old_name='detallesAdquisicion',
            new_name='detalleAdquisicion',
        ),
    ]
