# Generated by Django 3.1.7 on 2023-04-11 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModeloMaterial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelomaterial',
            old_name='idMaterial',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='modelomaterial',
            old_name='idModelo',
            new_name='modelo',
        ),
    ]
