# Generated by Django 3.1.7 on 2023-04-13 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Materiales', '0005_auto_20230404_1101'),
        ('FichasTecnicas', '0001_initial'),
        ('FichaTecnicaMaterial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnicamaterial',
            name='fichaTecnica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FichasTecnicas.fichatecnica'),
        ),
        migrations.AddField(
            model_name='fichatecnicamaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Materiales.material'),
        ),
    ]
