# Generated by Django 3.1.7 on 2023-04-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FichaTecnicaMaterial', '0002_auto_20230412_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichatecnicamaterial',
            name='peso',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
