# Generated by Django 3.1.7 on 2023-04-28 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FichasTecnicas', '0004_remove_fichatecnica_nombreprograma'),
        ('FichaTecnicaMaterial', '0003_auto_20230413_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichatecnicamaterial',
            name='fichaTecnica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FichasTecnicas.fichatecnica'),
        ),
    ]
