# Generated by Django 3.1.7 on 2023-05-20 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Materiales', '0005_auto_20230404_1101'),
        ('FichaTecnicaMaterial', '0004_auto_20230428_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichatecnicamaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Materiales.material'),
        ),
    ]
