# Generated by Django 3.1.7 on 2023-03-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='calibre',
            field=models.CharField(blank=True, choices=[('150', '150'), ('300', '300')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('Poliester', 'Poliester'), ('Melting', 'Melting'), ('Lurex', 'Lurex'), ('Goma', 'Goma'), ('Licra desnuda', 'Licra desnuda')], default='Políester', max_length=20),
        ),
    ]
