# Generated by Django 3.1.7 on 2023-03-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materiales', '0002_auto_20230314_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('Poliester', 'Poliester'), ('Melting', 'Melting'), ('Lurex', 'Lurex'), ('Goma', 'Goma'), ('Licra desnuda', 'Licra desnuda')], default='Poliester', max_length=20),
        ),
    ]
