# Generated by Django 3.1.7 on 2023-04-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materiales', '0003_auto_20230321_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='codigoColor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='tenida',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
