# Generated by Django 3.1.7 on 2023-06-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetallePedido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='paresPorPaquete',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='cantidades',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='rutaProduccion',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
