# Generated by Django 3.1.7 on 2023-06-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetallePedido', '0002_auto_20230603_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='colores',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='proveedores',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
