# Generated by Django 3.1.7 on 2023-04-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FichasTecnicas', '0002_fichatecnica_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichatecnica',
            name='archivoFichaTecnica',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='pesoLurex',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='pesoMelt',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='pesoPoliester',
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='fechaCreacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='fechaUltimaEdicion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
