# Generated by Django 3.1.7 on 2023-04-14 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FichasTecnicas', '0003_auto_20230413_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichatecnica',
            name='nombrePrograma',
        ),
    ]
