# Generated by Django 3.1.7 on 2023-02-22 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleados', '0001_initial'),
        ('Maquinas', '0003_auto_20230215_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoMaquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleado')),
                ('idMaquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maquinas.maquina')),
            ],
        ),
    ]
